### ISSUE TITLE
Unable to merge files 

### ISSUE THREAD

**Issue by joshirashmics** [boazsegev/combine_pdf#135]
I have been using combine_pdf for sometime and it works just fine. Thanks for this amazing gem.  However recently i created a new pdf and this pdf has issues merging with the bundle. I have attached all the pdfs that my program is trying to merge together. They are merged together as :
```
      merged_pdf = CombinePDF.new
      for file in pdfs_to_merge
        merged_pdf << CombinePDF.load(file)
      end
      @merge_file_path = "#{@temp_working_directory}/#{SecureRandom.uuid}-#{Time.now.to_i}.pdf"
      merged_pdf.save(@merge_file_path)
```

The exception stack trace is : 

```
A TypeError occurred in background at 2017-12-18 13:12:22 UTC :

  no implicit conversion of Symbol into Hash
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `merge'

  -------------------------------
Backtrace:
-------------------------------

  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `merge'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `hash_merge_new_no_page'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `merge'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `hash_merge_new_no_page'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `merge'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `hash_merge_new_no_page'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `merge'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `hash_merge_new_no_page'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `merge'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_protected.rb:263:in `hash_merge_new_no_page'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_public.rb:304:in `update'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_public.rb:304:in `insert'
  /Users/rashmijoshi/.rvm/gems/ruby-2.2.4/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_public.rb:274:in `<<'
[2de1df49-7a64-414e-b341-1e4b4398b47c-1513542148.pdf](https://github.com/boazsegev/combine_pdf/files/1568027/2de1df49-7a64-414e-b341-1e4b4398b47c-1513542148.pdf)
[4c0aa4c3-6e7e-49f6-b48a-649d32c07d6a-1513542149.pdf](https://github.com/boazsegev/combine_pdf/files/1568028/4c0aa4c3-6e7e-49f6-b48a-649d32c07d6a-1513542149.pdf)
[929d95dc-4f3b-4d80-a7e7-cf65c3fd93b1-1513542148.pdf](https://github.com/boazsegev/combine_pdf/files/1568029/929d95dc-4f3b-4d80-a7e7-cf65c3fd93b1-1513542148.pdf)
[6292e233-cef3-4bbe-8e94-fc8054e4c8d7-1513542148.pdf](https://github.com/boazsegev/combine_pdf/files/1568030/6292e233-cef3-4bbe-8e94-fc8054e4c8d7-1513542148.pdf)
[77323fb3-10c4-4d38-b587-cb33dd0dc7cd-1513542149.pdf](https://github.com/boazsegev/combine_pdf/files/1568031/77323fb3-10c4-4d38-b587-cb33dd0dc7cd-1513542149.pdf)
[a8233dc4-2911-45a5-b5b0-279280fe6289-1513542149.pdf](https://github.com/boazsegev/combine_pdf/files/1568032/a8233dc4-2911-45a5-b5b0-279280fe6289-1513542149.pdf)
[bd6df62a-de56-44ad-8921-993d47257e1a-1513542149.pdf](https://github.com/boazsegev/combine_pdf/files/1568033/bd6df62a-de56-44ad-8921-993d47257e1a-1513542149.pdf)
[cc560471-3fef-4ca4-a36b-870ed14a2a4a-1513542149.pdf](https://github.com/boazsegev/combine_pdf/files/1568034/cc560471-3fef-4ca4-a36b-870ed14a2a4a-1513542149.pdf)








```

**Comment by boazsegev** [comment]
Hi @joshirashmics ,

Thank you for opening this issue.

I am currently traveling, but I will do my best to look this over as soon as I can.

Bo.

**Comment by boazsegev** [comment]
@joshirashmics 

I noticed that you're using CombinePDF version 0.2.30.

Could you upgrade to version 1.0.7 and see if this resolves your issue?

I couldn't reproduce the issue using my development version.

Thanks!
  Bo.

**Comment by joshirashmics** [comment]
Thanks for the response @boazsegev I will try upgrading the version and will let yo know.

**Comment by joshirashmics** [comment]
Hi Bo, updating the gem fixed it. Thank you so much and sorry for the false alarm.

**Comment by boazsegev** [comment]
Hi @joshirashmics, thanks for letting me know! :-)
