### ISSUE TITLE
Parsing specific PDF in 1.0.21 - RangeError: index out of range (works in 1.0.20)

### ISSUE THREAD

**Issue by Laykou** [boazsegev/combine_pdf#205]
When trying to parse this PDF [rose_production_split_pages.pdf](https://github.com/boazsegev/combine_pdf/files/7900814/rose_production_split_pages.pdf), we're getting error:

```
 RangeError:
       index out of range
      # /Users/laykou/.rvm/gems/ruby-3.1.0/gems/combine_pdf-1.0.22/lib/combine_pdf/parser.rb:364:in `pos='
     # /Users/laykou/.rvm/gems/ruby-3.1.0/gems/combine_pdf-1.0.22/lib/combine_pdf/parser.rb:364:in `_parse_'
     # /Users/laykou/.rvm/gems/ruby-3.1.0/gems/combine_pdf-1.0.22/lib/combine_pdf/parser.rb:79:in `parse'
     # /Users/laykou/.rvm/gems/ruby-3.1.0/gems/combine_pdf-1.0.22/lib/combine_pdf/pdf_public.rb:98:in `initialize'
     # /Users/laykou/.rvm/gems/ruby-3.1.0/gems/combine_pdf-1.0.22/lib/combine_pdf/api.rb:40:in `new'
     # /Users/laykou/.rvm/gems/ruby-3.1.0/gems/combine_pdf-1.0.22/lib/combine_pdf/api.rb:40:in `parse'
```

How we call it:

```ruby
CombinePDF.parse(blob.download, allow_optional_content: true).pages
```

This happens on version `1.0.21` and `1.0.22` however not on `1.0.20`.

Now we wanted to move to Ruby 3.1 and we need _matrix_ fix which is in `1.0.22` but  we cannot upgrade because of this failing PDF example.

**Comment by Laykou** [comment]
@boazsegev For some reason this fix https://github.com/boazsegev/combine_pdf/commit/b966e703fd897ff50832d3823e74791099b82ca3 broke it

**Comment by boazsegev** [comment]
Hi @Laykou 

Thank you for opening this issue.

Please note my comments: [here for issue #185](https://github.com/boazsegev/combine_pdf/issues/185#issuecomment-768270331) and [here for issue #191](https://github.com/boazsegev/combine_pdf/issues/191#issuecomment-815336809).

I usually prefer lax parsers that allow formatting errors to be ignored when possible. However, issue #185 showed that a specific type of error cannot be safely ignored, which required that the parser become more strict.

I strongly suspect, from the description of the issue, that the specific PDF file is malformed.

Testing the PDF @ https://www.datalogics.com/products/pdf-tools/pdf-checker/ **fails** ... the testing suite doesn't even recognize the file as a PDF, not to mention listing the errors.

I have been authoring and maintaining this gem by myself for over 7 years and have been looking for a new maintainer for over 2 years. The community is enjoying my work, but not really contributing, so... 🤷🏼‍♂️ ... please forgive me for not investing more time and effort to solve this issue.

Kindly,
   Bo.

**Comment by DimaSamodurov** [comment]
Hi @boazsegev ,
It appears that the Length property of the stream can be incorrect in more cases than the presence of the 'endstream' keyword within the content. Anyway, preferring one over another way to extending the scanner position leads to issues. 
Many of these issues are acceptable for the end users, provided result looks well. E.g. swallowing the "index is out of range" error would fix the parsing of the file attached. Then it can be combined and work can be done. 
Can we swallow the error and warn for this case?

**Comment by Laykou** [comment]
Do you think this could be fixed in a newer versino?

**Comment by julitrows** [comment]
Getting `index out of range (RangeError)` on a user uploaded PDF in version 1.0.26 as well.

**Comment by mtwzim** [comment]
> Hi @Laykou
> 
> Thank you for opening this issue.
> 
> Please note my comments: [here for issue #185](https://github.com/boazsegev/combine_pdf/issues/185#issuecomment-768270331) and [here for issue #191](https://github.com/boazsegev/combine_pdf/issues/191#issuecomment-815336809).
> 
> I usually prefer lax parsers that allow formatting errors to be ignored when possible. However, issue #185 showed that a specific type of error cannot be safely ignored, which required that the parser become more strict.
> 
> I strongly suspect, from the description of the issue, that the specific PDF file is malformed.
> 
> Testing the PDF @ https://www.datalogics.com/products/pdf-tools/pdf-checker/ **fails** ... the testing suite doesn't even recognize the file as a PDF, not to mention listing the errors.
> 
> I have been authoring and maintaining this gem by myself for over 7 years and have been looking for a new maintainer for over 2 years. The community is enjoying my work, but not really contributing, so... 🤷🏼‍♂️ ... please forgive me for not investing more time and effort to solve this issue.
> 
> Kindly, Bo.

There are some pull requests created that could possibly solve this problem but so far they have not been merged and the problem occurs even after almost a year after PRs were submitted.

https://github.com/boazsegev/combine_pdf/pull/209
https://github.com/boazsegev/combine_pdf/pull/215

**Comment by Kaiito630** [comment]
Hello, getting 'RangeError: index out of range' on 1.0.23 version as well

**Comment by boazsegev** [comment]
Should be resolved in `1.0.31` - can you please see if the `1.0.30beta` release resolves your issue?

**Comment by KISZCZ-R** [comment]
I noticed the following case, which fails in version `1.0.31`. The PDF contains the following stream object definition:
```
8 0 obj
<</Length 3300
/Type
/Metadata
/Subtype 
/XML>>
stream
endstream
endobj
```
The `/Length` attribute is invalid. The parser can handle missing or corrupted lengths, but in this case, the specified length points outside the file content, which results in a `RangeError` at the following line:
```
lib/combine_pdf/parser.rb:365    @scanner.pos += out.last[:Length] # It should check if next pos is within bounds. If not fallback to scanning for endstream tag
```

Other parsers, such as built-in browser PDF viewers, handle this gracefully and render the PDF correctly. So, it may be worth considering a fix.

**Comment by Laykou** [comment]
I checked and even in version `1.0.31` the PDF file I used 3 years ago still keeps failing on RangeError

**Comment by jannewaren** [comment]
@Laykou can you try your file with my branch https://github.com/jannewaren/combine_pdf/tree/fix-index-out-of-range-error, would it work?

**Comment by Laykou** [comment]
It worked without an issue. Would you have this merged into combine_pdf and released?
