### ISSUE TITLE
[WIP]: SystemStackError: stack level too deep when parsing specific PDF files with `catalogs[:Resources]`

### ISSUE THREAD

**Issue by tagliala** [boazsegev/combine_pdf#242]
Refers to #214, but it is not the same issue

I can't replicate #214 with the same use case because I'm getting `malformed PDF file?` error

Unfortunately I can't share the file, but this is the error

```
SystemStackError: 7657 -> 37
     +->> 3812 cycles of 2 lines:
     | ~/dev/combine_pdf/lib/combine_pdf/parser.rb:737:in `merge'
     | ~/combine_pdf/lib/combine_pdf/parser.rb:737:in `block in <class:PDFParser>'
     +-<<
```

It is happening here:

https://github.com/boazsegev/combine_pdf/blob/fe11372f16dfd1a18d50f88280b1e4c102f178ce/lib/combine_pdf/parser.rb#L547

I've tested against some open PRs, several versions of combine_pdf, and checked existing issues, unfortunately there's no solution at the moment

I'm still investigating

Standalone reproducible test case (can't provide the file, sorry)

```rb
#!/usr/bin/env ruby

# frozen_string_literal: true

FILE = ARGV[0]

if FILE.nil?
  puts "Usage: #{File.basename($0)} path.to.pdf"
  exit 1
elsif !File.exist?(FILE)
  puts "File '#{FILE}' not found"
  exit 1
end

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'combine_pdf'
  gem 'minitest'
end

require 'combine_pdf'
require 'minitest/autorun'

class BugTest < Minitest::Test
  def test_combine_pdf_parse
    assert CombinePDF.load(FILE)
  end
end
```

```
> puts catalogs[:Resources][:referenced_object].keys.inspect

[:Font, :XObject, :ExtGState, :ProcSet, :indirect_generation_number, :indirect_reference_id]
```

**Comment by tagliala** [comment]
Question: Is "HASH_UPDATE_PROC_FOR_OLD" a self implementation of a `reverse_deep_merge` ?

**Comment by pardeyke** [comment]
I ran into the same overflow and tracked down the cause: the page's `/Resources` dictionary contains an XObject (a LibreOffice transparency group, `/Tr4` in my file) whose own `/Resources` points back at the same dictionary. The `Pages` node and the `Page` share that dictionary, so `HASH_UPDATE_PROC_FOR_OLD` ends up merging an object with itself and follows the cycle forever.

A ten-line Prawn script reproduces it without any private data, and skipping the merge when `old_data.equal?(new_data)` fixes it. PR with fix, fixture and specs: #258
