### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by iggant** [boazsegev/combine_pdf#54]
with some pdfs I have strange error: 

```code
NoMethodError: undefined method `[]' for nil:NilClass
	from /path_to_gem/ruby/2.2.0/gems/combine_pdf-0.2.17/lib/combine_pdf/page_methods.rb:876:in `block (2 levels) in should_secure?'
```

I have digg into that code and debug that v variable has this value:
```code
{:F6=>{:is_reference_only=>true, :referenced_object=>{:Type=>:Font, :Subtype=>:TrueType, :BaseFont=>:"Arial-BoldMT", :FirstChar=>30, :LastChar=>255, :Encoding=>:WinAnsiEncoding, :Widths=>[750, 750, 278, 333, 474, 556, 556, 889, 722, 238, 333, 333, 389, 584, 278, 333, 278, 278, 556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 333, 333, 584, 584, 584, 611, 975, 722, 722, 722, 722, 667, 611, 778, 722, 278, 556, 722, 611, 833, 722, 778, 667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 333, 278, 333, 584, 556, 333, 556, 611, 556, 611, 556, 333, 611, 611, 278, 278, 556, 278, 889, 611, 611, 611, 611, 389, 556, 333, 611, 556, 778, 556, 556, 500, 389, 280, 389, 584, 750, 556, 750, 278, 556, 500, 1000, 556, 556, 333, 1000, 667, 333, 1000, 750, 611, 750, 750, 278, 278, 500, 500, 350, 556, 1000, 333, 1000, 556, 333, 944, 750, 500, 667, 278, 333, 556, 556, 556, 556, 280, 556, 333, 737, 370, 556, 584, 333, 737, 552, 400, 549, 333, 333, 333, 576, 556, 333, 333, 333, 365, 556, 834, 834, 834, 611, 722, 722, 722, 722, 722, 722, 1000, 722, 667, 667, 667, 667, 278, 278, 278, 278, 722, 722, 778, 778, 778, 778, 778, 584, 778, 722, 722, 722, 722, 667, 667, 611, 556, 556, 556, 556, 556, 556, 889, 556, 556, 556, 556, 556, 278, 278, 278, 278, 611, 611, 611, 611, 611, 611, 611, 549, 611, 611, 611, 611, 611, 556, 611, 556], :FontDescriptor=>{:is_reference_only=>true, :referenced_object=>{:Type=>:FontDescriptor, :Ascent=>728, :CapHeight=>0, :Descent=>-210, :Flags=>42, :FontBBox=>[-628, -376, 2000, 1018], :FontName=>:Arial_Bold, :ItalicAngle=>0, :StemV=>0}}}}, :F7=>{:is_reference_only=>true, :referenced_object=>{:Type=>:Font, :Subtype=>:TrueType, :BaseFont=>:ArialMT, :FirstChar=>30, :LastChar=>255, :Encoding=>:WinAnsiEncoding, :Widths=>[750, 750, 278, 278, 355, 556, 556, 889, 667, 191, 333, 333, 389, 584, 278, 333, 278, 278, 556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 584, 584, 584, 556, 1015, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778, 667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 278, 278, 278, 469, 556, 333, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556, 556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 334, 260, 334, 584, 750, 556, 750, 222, 556, 333, 1000, 556, 556, 333, 1000, 667, 333, 1000, 750, 611, 750, 750, 222, 222, 333, 333, 350, 556, 1000, 333, 1000, 500, 333, 944, 750, 500, 667, 278, 333, 556, 556, 556, 556, 260, 556, 333, 737, 370, 556, 584, 333, 737, 552, 400, 549, 333, 333, 333, 576, 537, 333, 333, 333, 365, 556, 834, 834, 834, 611, 667, 667, 667, 667, 667, 667, 1000, 722, 667, 667, 667, 667, 278, 278, 278, 278, 722, 722, 778, 778, 778, 778, 778, 584, 778, 722, 722, 722, 722, 667, 667, 611, 556, 556, 556, 556, 556, 556, 889, 500, 556, 556, 556, 556, 278, 278, 278, 278, 556, 556, 556, 556, 556, 556, 556, 549, 611, 556, 556, 556, 556, 500, 556, 500], :FontDescriptor=>{:is_reference_only=>true, :referenced_object=>{:Type=>:FontDescriptor, :Ascent=>728, :CapHeight=>0, :Descent=>-210, :Flags=>42, :FontBBox=>[-665, -325, 2000, 1006], :FontName=>:Arial, :ItalicAngle=>0, :StemV=>0}}}}, :F21=>{:is_reference_only=>true, :referenced_object=>{:Type=>:Font, :Subtype=>:TrueType, :BaseFont=>:"Arial-ItalicMT", :FirstChar=>30, :LastChar=>255, :Encoding=>:WinAnsiEncoding, :Widths=>[750, 750, 278, 278, 355, 556, 556, 889, 667, 191, 333, 333, 389, 584, 278, 333, 278, 278, 556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 584, 584, 584, 556, 1015, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778, 667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 278, 278, 278, 469, 556, 333, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556, 556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 334, 260, 334, 584, 750, 556, 750, 222, 556, 333, 1000, 556, 556, 333, 1000, 667, 333, 1000, 750, 611, 750, 750, 222, 222, 333, 333, 350, 556, 1000, 333, 1000, 500, 333, 944, 750, 500, 667, 278, 333, 556, 556, 556, 556, 260, 556, 333, 737, 370, 556, 584, 333, 737, 552, 400, 549, 333, 333, 333, 576, 537, 333, 333, 333, 365, 556, 834, 834, 834, 611, 667, 667, 667, 667, 667, 667, 1000, 722, 667, 667, 667, 667, 278, 278, 278, 278, 722, 722, 778, 778, 778, 778, 778, 584, 778, 722, 722, 722, 722, 667, 667, 611, 556, 556, 556, 556, 556, 556, 889, 500, 556, 556, 556, 556, 278, 278, 278, 278, 556, 556, 556, 556, 556, 556, 556, 549, 611, 556, 556, 556, 556, 500, 556, 500], :FontDescriptor=>{:is_reference_only=>true, :referenced_object=>{:Type=>:FontDescriptor, :Ascent=>728, :CapHeight=>0, :Descent=>-208, :Flags=>106, :FontBBox=>[-517, -325, 1359, 998], :FontName=>:Arial_Italic, :ItalicAngle=>-12, :StemV=>0}}}}, :F37=>{:is_reference_only=>true, :referenced_object=>{:Type=>:Font, :Subtype=>:TrueType, :BaseFont=>:"Arial-BoldItalicMT", :FirstChar=>30, :LastChar=>255, :Encoding=>:WinAnsiEncoding, :Widths=>[750, 750, 278, 333, 474, 556, 556, 889, 722, 238, 333, 333, 389, 584, 278, 333, 278, 278, 556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 333, 333, 584, 584, 584, 611, 975, 722, 722, 722, 722, 667, 611, 778, 722, 278, 556, 722, 611, 833, 722, 778, 667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 333, 278, 333, 584, 556, 333, 556, 611, 556, 611, 556, 333, 611, 611, 278, 278, 556, 278, 889, 611, 611, 611, 611, 389, 556, 333, 611, 556, 778, 556, 556, 500, 389, 280, 389, 584, 750, 556, 750, 278, 556, 500, 1000, 556, 556, 333, 1000, 667, 333, 1000, 750, 611, 750, 750, 278, 278, 500, 500, 350, 556, 1000, 333, 1000, 556, 333, 944, 750, 500, 667, 278, 333, 556, 556, 556, 556, 280, 556, 333, 737, 370, 556, 584, 333, 737, 552, 400, 549, 333, 333, 333, 576, 556, 333, 333, 333, 365, 556, 834, 834, 834, 611, 722, 722, 722, 722, 722, 722, 1000, 722, 667, 667, 667, 667, 278, 278, 278, 278, 722, 722, 778, 778, 778, 778, 778, 584, 778, 722, 722, 722, 722, 667, 667, 611, 556, 556, 556, 556, 556, 556, 889, 556, 556, 556, 556, 556, 278, 278, 278, 278, 611, 611, 611, 611, 611, 611, 611, 549, 611, 611, 611, 611, 611, 556, 611, 556], :FontDescriptor=>{:is_reference_only=>true, :referenced_object=>{:Type=>:FontDescriptor, :Ascent=>728, :CapHeight=>0, :Descent=>-210, :Flags=>106, :FontBBox=>[-560, -376, 1390, 1018], :FontName=>:Arial_Bold_Italic, :ItalicAngle=>-12, :StemV=>0}}}}, :F63=>{:is_reference_only=>true, :referenced_object=>{:Type=>:Font, :Subtype=>:TrueType, :BaseFont=>:"TimesNewRomanPS-BoldMT", :FirstChar=>30, :LastChar=>255, :Encoding=>:WinAnsiEncoding, :Widths=>[778, 778, 250, 333, 555, 500, 500, 1000, 833, 278, 333, 333, 500, 570, 250, 333, 250, 278, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 333, 333, 570, 570, 570, 500, 930, 722, 667, 722, 722, 667, 611, 778, 778, 389, 500, 778, 667, 944, 722, 778, 611, 778, 722, 556, 667, 722, 722, 1000, 722, 722, 667, 333, 278, 333, 581, 500, 333, 500, 556, 444, 556, 444, 333, 500, 556, 278, 333, 556, 278, 833, 556, 500, 556, 556, 444, 389, 333, 556, 500, 722, 500, 500, 444, 394, 220, 394, 520, 778, 500, 778, 333, 500, 500, 1000, 500, 500, 333, 1000, 556, 333, 1000, 778, 667, 778, 778, 333, 333, 500, 500, 350, 500, 1000, 333, 1000, 389, 333, 722, 778, 444, 722, 250, 333, 500, 500, 500, 500, 220, 500, 333, 747, 300, 500, 570, 333, 747, 500, 400, 549, 300, 300, 333, 576, 540, 333, 333, 300, 330, 500, 750, 750, 750, 500, 722, 722, 722, 722, 722, 722, 1000, 722, 667, 667, 667, 667, 389, 389, 389, 389, 722, 722, 778, 778, 778, 778, 778, 570, 778, 722, 722, 722, 722, 722, 611, 556, 500, 500, 500, 500, 500, 500, 722, 444, 444, 444, 444, 444, 278, 278, 278, 278, 500, 556, 500, 500, 500, 500, 500, 549, 500, 556, 556, 556, 556, 500, 556, 500], :FontDescriptor=>{:is_reference_only=>true, :referenced_object=>{:Type=>:FontDescriptor, :Ascent=>677, :CapHeight=>0, :Descent=>-216, :Flags=>42, :FontBBox=>[-558, -307, 2000, 1026], :FontName=>:Times_New_Roman_Bold, :ItalicAngle=>0, :StemV=>0}}}}, :F65=>{:is_reference_only=>true, :referenced_object=>{:Type=>:Font, :Subtype=>:TrueType, :BaseFont=>:"TimesNewRomanPS-ItalicMT", :FirstChar=>30, :LastChar=>255, :Encoding=>:WinAnsiEncoding, :Widths=>[778, 778, 250, 333, 420, 500, 500, 833, 778, 214, 333, 333, 500, 675, 250, 333, 250, 278, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 333, 333, 675, 675, 675, 500, 920, 611, 611, 667, 722, 611, 611, 722, 722, 333, 444, 667, 556, 833, 667, 722, 611, 722, 611, 500, 556, 722, 611, 833, 611, 556, 556, 389, 278, 389, 422, 500, 333, 500, 500, 444, 500, 444, 278, 500, 500, 278, 278, 444, 278, 722, 500, 500, 500, 500, 389, 389, 278, 500, 444, 667, 444, 444, 389, 400, 275, 400, 541, 778, 500, 778, 333, 500, 556, 889, 500, 500, 333, 1000, 500, 333, 944, 778, 556, 778, 778, 333, 333, 556, 556, 350, 500, 889, 333, 980, 389, 333, 667, 778, 389, 556, 250, 389, 500, 500, 500, 500, 275, 500, 333, 760, 276, 500, 675, 333, 760, 500, 400, 549, 300, 300, 333, 576, 523, 250, 333, 300, 310, 500, 750, 750, 750, 500, 611, 611, 611, 611, 611, 611, 889, 667, 611, 611, 611, 611, 333, 333, 333, 333, 722, 667, 722, 722, 722, 722, 722, 675, 722, 722, 722, 722, 722, 556, 611, 500, 500, 500, 500, 500, 500, 500, 667, 444, 444, 444, 444, 444, 278, 278, 278, 278, 500, 500, 500, 500, 500, 500, 500, 549, 500, 500, 500, 500, 500, 444, 500, 444], :FontDescriptor=>{:is_reference_only=>true, :referenced_object=>{:Type=>:FontDescriptor, :Ascent=>694, :CapHeight=>0, :Descent=>-216, :Flags=>106, :FontBBox=>[-498, -307, 1333, 1023], :FontName=>:Times_New_Roman_Italic, :ItalicAngle=>-16, :StemV=>0}}}}, :F68=>{:is_reference_only=>true, :referenced_object=>{:Type=>:Font, :Subtype=>:TrueType, :BaseFont=>:TimesNewRomanPSMT, :FirstChar=>30, :LastChar=>255, :Encoding=>:WinAnsiEncoding, :Widths=>[778, 778, 250, 333, 408, 500, 500, 833, 778, 180, 333, 333, 500, 564, 250, 333, 250, 278, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 278, 278, 564, 564, 564, 444, 921, 722, 667, 667, 722, 611, 556, 722, 722, 333, 389, 722, 611, 889, 722, 722, 556, 722, 667, 556, 611, 722, 722, 944, 722, 722, 611, 333, 278, 333, 469, 500, 333, 444, 500, 444, 500, 444, 333, 500, 500, 278, 278, 500, 278, 778, 500, 500, 500, 500, 333, 389, 278, 500, 500, 722, 500, 500, 444, 480, 200, 480, 541, 778, 500, 778, 333, 500, 444, 1000, 500, 500, 333, 1000, 556, 333, 889, 778, 611, 778, 778, 333, 333, 444, 444, 350, 500, 1000, 333, 980, 389, 333, 722, 778, 444, 722, 250, 333, 500, 500, 500, 500, 200, 500, 333, 760, 276, 500, 564, 333, 760, 500, 400, 549, 300, 300, 333, 576, 453, 333, 333, 300, 310, 500, 750, 750, 750, 444, 722, 722, 722, 722, 722, 722, 889, 667, 611, 611, 611, 611, 333, 333, 333, 333, 722, 722, 722, 722, 722, 722, 722, 564, 722, 722, 722, 722, 722, 722, 556, 500, 444, 444, 444, 444, 444, 444, 667, 444, 444, 444, 444, 444, 278, 278, 278, 278, 500, 500, 500, 500, 500, 500, 500, 549, 500, 500, 500, 500, 500, 500, 500, 500], :FontDescriptor=>{:is_reference_only=>true, :referenced_object=>{:Type=>:FontDescriptor, :Ascent=>693, :CapHeight=>0, :Descent=>-216, :Flags=>42, :FontBBox=>[-568, -307, 2000, 1007], :FontName=>:Times_New_Roman, :ItalicAngle=>0, :StemV=>0}}}}, :R8=>{:is_reference_only=>true, :referenced_object=>{:BaseFont=>:"OKDLIF+Helvetica,Bold", :FontDescriptor=>{:is_reference_only=>true, :referenced_object=>{:Type=>:FontDescriptor, :FontName=>:"OKDLIF+Helvetica,Bold", :FontBBox=>[-22, -218, 703, 729], :Flags=>32, :Ascent=>729, :CapHeight=>729, :Descent=>-218, :ItalicAngle=>0, :StemV=>105, :MissingWidth=>500, :XHeight=>549, :CharSet=>"/A/D/T/d/f/five/nine/one/p/two/underscore/zero", :FontFile3=>{:is_reference_only=>true, :referenced_object=>{:Filter=>:FlateDecode, :Subtype=>:Type1C, :Length=>1132, :raw_stream_content=>"x\x9CU\x92}LSW\x18\xC6\xCF\xA5\xED\xA5\xB2R(\xE4\xA2\x13\xA1W7\x04*\x90B`\xC0\x808\xF9(\r\x12\x1D\xA2\xA2\xE0\xE4\xB3\xC0\r-E)\fp\f'[\x82\x1C]\x96\x00c\x0E\xA4\x01\x01\x91\x8D\xAF\x11X\x14\xE7`S7]\x18\xE0\x12!\v\x92\x18\x83(\x1A$\x83\xEC\xBD\xE4\xD4d\xA7\x9B\xCB\xB2?\xEE\xCD=\xCF9\xEF\xB9\xBF\xE7y_\x06I\x1D\x10\xC30.z\x83\xB1\xDC`\x11r\xB3\x03b\xCD\xC6<\xBB\x14 z2\xE26\a\xD1KRF\x8A7R7L2/\x94\xDC\xFA\xC4\x19+$X!\xED\xDE&\xEDu\x83v\x15\xD4\xB9@\x95+\x920LE}s\x9C\xB9\xA4\xF2\xA4PPh\xE1\xFD\x0E\x1DH\xF3\xDF\xB5+\xE0?%822\x92\xCF\xA9\xFCw\x87\x8F7\x94\n\x05\xC5\xFCN\xFAQn0\x9AKL\x86bK\x14\x1FGO\e\x8DB._`\xAC,),\xE5\xB3\xF3\xF2\fy\xF6\xB2\xC3\xD9FC\x11\xAF\x13\x8CBI\x89\xB9\x9C\xF7\x8B\xF3\xE7C\xB4\xDA\xE0@\xFA\n\xDB'\x98r\xCAJ\xF9\xD4\xEC\xE2R>\x99\xB7\xF3\xFFOA\b)\xF6\x94\xC4\xE7\xE5\x1F\x8C\xCC\xD4\x06\x87\x84!\xB4\x03\xA5 \x1F\x94\x80\x12Q\x18\xDA\x8A\xDEA*\xE4\x86\xDC\x91\ar\xA6Y )\x15Z\xD02\x13\xC7|\xC8\xB4;\xB8;\xF88t;\xFC,yCR#\xD6)7\xF2\xB1\x15\xDCA\x05\x17\xAD\x10`e\xC4\xB3\xE0\xCB\x8D\x11_\x19\x04\xB1\xE43\x9A\x10y\x9B%\xCD/M2\bd\xAF\x03\x95?\x00\x15G\x0E\xB0\xCB0$S\x8A@\x8A\xAD\x10\v\x9B`\t61\xB7\x80\x87\xD3\xC0K ]\x1C\xE4\b\xFF\xB2\x9E\xAE\xFB\xD9\xBE\xFDc\xE6),\a\x8Fg\xA0\x84\x88\xD9\xB2\xD9\x82\xEF\xD4\x057\xF4}I8\x11g\x14\v\xFB\xE5\xE0d\xE6\xEE]\xD3\xBD\xE9\x9F\xAE\xD3%dL\xAD\xAE\x8EM\xCF\xA8\xEDX\xA0\x12KA\xC5\xCC\x81\x06n\x82F2\xE7\x01C,H\xF0L\xD7\xF5\xDB\xB7\xA6zW0\xC80H\x8D+)\xD3\xE9\xB7u\x9DD\x8A\xE5\x84\xEEkl\xAB\x1C-\xF3t\x04\xD9\x8F\xD1$\x8C\x84\xA6F\x13\x99\x9A\x92Z(\xE5c\xFA\x84Z\x99\x9EW\xA0\xA2\xBF\a\xF0\e&\xC2\x93f\xB6p\xE2X\xA7\x9E^\xC1\xF9\x13W\x12\x1E\xDB\xBEg M=\x986)L\xE2_\xF1\xB5\xCE\xFEq9q\x12\x9D\xFF\xE1\xCCHLH\xC8\x98^y16C9\xE1!\xB6\x8A\xA1O\x96\xD7\x99E\xBB\xF5I\xB1\x8B\x8B\x18g/7_\xE8jn\xA9?\xDB\xEC\xBD\xEEx\xE2|\xE1\xB9\n,\x0F:\x9E\xA9U'\xED\x0E\x9A\xB5\xE9\x81\x17\xF5\v\x8E\x94\x89\x96\xCES\x87PC\xED\x89\x9C\xB8\xCA\x81\x00*\xDB<Q\xC1\t\xDB*hX\xA58^\n\n\xD8\x02rh\x03\x96\xB9\f\xAFK\x86 \x92\xFB\x940KQ\xA0\xC4\x8F\xF1\xF4\xD0\xC8o\x83w\xDB\xFF\xC4\xC0\xE2?\xAA\x1E\x14\x8D\x1F\x9FM\x18~\x8B\xDA\xD8\xA1\xF1!~d\xE7C_p\e\xE8kjiW\x7F\xD1\xD8\xD0\xD8\xD1%'\x9E\x06}t\xBA\xD0=R\xE7\xBD(\xA6pS#\x87#b2\xD3\xF6\xEE\xCD\xBD1\xFF`\xF8\xFB;4\xA8q\x922\xCD\x88\xF7\x89\x82\xB3=\xD7\x89\xCF\xED\f\x16P\x88\x9F\x83\xEC\xEF\xDC\xF2\xEC.\xBB6\n\xB9\xDD8\xA9(\xEB\xDD\x9C\x83\x15ZL\xBC0Q\xB5\x86|}hD?mX\xC0s\xF8n\xEF\xB7?\rOX\x970l\xC1\xE0q\xEA\x91\xF0C\xF6\x94n0\x82r\xC9\xA4\x03\xB8\xE7\xFD\xD6\xFC\v\xA6\x86\x18\xAC\xC1\xD1\xB5Q\x1F\x99Oe\x9B,\xB98\x1F\x9B\xDB\xAA\x06\xAA\xAF\xD4\xDE\xC7O\xF1B\xC3|SO\xCB\xE8\x95K\xC3XN\x01\xB0\x95\x813\xF6\x1F\x9F\x11\xAB9[5m\xDA\xD1 \xC7\xB2\xF0\xD8,\xA2\xA4\xC1:\xDAO\xD0a\xA9\xA4\x11}\x03\x9E\xF0\x9E\xBD\xB5\x8D\xF61\x1Dg/\x0E\xB5[\xD7f\xC1eq`\x02?\x93\x83W\xE0#\xE2O|\xC3B\x89\xE6\x13\\{\xEE\xB47l\xED`\x7F\x1F\xBC\xFA\xCB\x9D\xA1\xAC\xF8\x98\x93F\xA2%\x12o\xA2\x88\xCCO\xFE\x98l\x96\x8B\xE5\xAF\xDC\xC3%\x90\xAC\xD3F\x89\xCE\xF6\xAB\xAB7\x8Er6\x176\xD9\xA6\x96\x81\e\xFBe\xFFWm\xA3X~o\xF4HXD\xE6\x91\x84}B\xEF\xCD:5\xF1f\xCF\x13\xD7\xA7\xE1\xE0M'?`m\r\x02\xC1'\xF8\x05\xD9|\xAC\xB0\xC6\x98\xA3\xEE\x00?\x19\\e\x95\x96\x0Eq\xD0\n1\xD6\x8C\x0E\x16\x9C\x9C`\xFBk\xE0\xD4\xA8P\xC0\xF6&\x853B\x7F\x01\xE0s6%"}}}}, :Type=>:Font, :FirstChar=>48, :LastChar=>112, :Widths=>[556, 556, 556, 0, 0, 556, 0, 0, 0, 556, 0, 0, 0, 0, 0, 0, 0, 722, 0, 0, 722, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 611, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 0, 0, 0, 0, 611, 0, 333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 611], :Encoding=>:WinAnsiEncoding, :Subtype=>:Type1}}}
```
while k is equal to :Font

so as a work arround add additional check actual_value(v[k]) to this string: 

```code
v.keys.each do |name| return true if actual_value(foreign_res[k]) && actual_value(foreign_res[k])[name] && actual_value(v[k]) && actual_value(foreign_res[k])[name] != actual_value(v[k])[name]
code

**Comment by boazsegev** [comment]
Hi Anton,

Thank you very much for opening this issue.

I would like to check this a bit further before I implement a patch to the library. Could you send me an example PDF?

Thanks!
   Bo.

**Comment by boazsegev** [comment]
Hi Anton,

Again I wanted to thank you for posting this issue. I was wondering if you had an example for me, as I couldn't reproduce the issue.

This also helps with testing, as I have a bank of examples I test against. All these examples have known issues (or cause known issues) that were resolved. Testing against these examples helps me ensure that future updates don't break existing patches. This is why having an example is important to me.

Thank you for your help.

**Comment by iggant** [comment]
@boazsegev 

I'm very sorry, but for now I can't provide you with pdf file, because this file clients upload us, and this is not supposed to share. 

Every file which I generate to test pass this without error. 
I'll try some different approch, and I'll back if success

**Comment by cw6365** [comment]
Hi @boazsegev 

I have a similar issue. 

[15] pry(#<PdfTasks>)> page << textpdf.pages[index]
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/chrisward/.rvm/gems/ruby-1.9.3-p551@esign/gems/combine_pdf-0.2.17/lib/combine_pdf/page_methods.rb:876:in `block (2 levels) in should_secure?'

textpdf = CombinePDF.load text_path
    contentpdf = CombinePDF.load pdf_path
    contentpdf.pages.each_with_index do |page, index|
      unless textpdf.pages[index].nil?
<!!!--- issue is caused by the line below -->
        page << textpdf.pages[index]
      end
    end
    contentpdf.save pdf_path

I can email you the file if needed.

**Comment by boazsegev** [comment]
Hi Chris (@cw6365 ),

Thanks for letting me know. I'd be happy to get a copy of the file so I can reproduce the issue and implement a patch.

Thanks!

Bo.

**Comment by boazsegev** [comment]
@cw6365 , @iggant ,

I uploaded a patch to the `page_methods.rb` file.

Since I can't reproduce the issue, I have no idea if it's any better.

Can you test this?

**Comment by cw6365** [comment]
Thanks @boazsegev i'll test in the morning. I'm not positive but i think the problem may be with the line

`contentpdf.pages.each_with_index do |page, index|`

I think it 99% of cases `page` is normally another array, hence `page << textpdf.pages[index]` but this time it's just an object. I'm not sure why in this case though as it's been live on production and working well in most instances.

I've also re-tested the file and it works on a different account. Strange one.

**Comment by cw6365** [comment]
I've also sent the doc too.

**Comment by boazsegev** [comment]
page should always be an object (a Hash, to be specific). The `<<` is a PDF Page object, not an Array `push`.

Page Hash objects are extended using the [Page_Methods](https://github.com/boazsegev/combine_pdf/blob/c6e76e2a2189a62e53929b5a1187bc7e5ea0a6e7/lib/combine_pdf/page_methods.rb#L47-L92) module.

**Comment by boazsegev** [comment]
Hi @cw6365 ,

Thanks for the document!

I still can't seem to reproduce, but maybe the patch works.

**Comment by cw6365** [comment]
The patch worked thanks!

**Comment by boazsegev** [comment]
Thanks for letting me know, I'll release the update soon. :-)

**Comment by iggant** [comment]
@boazsegev 

thank you, I can also confirm that all work fine

**Comment by boazsegev** [comment]
@iggant , Thanks for letting me know :)
